"""empty message

Revision ID: bda56fc6bc90
Revises: 
Create Date: 2022-09-23 13:06:09.261360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda56fc6bc90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_no', sa.String(length=10), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('txn_type', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.String(length=10), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('agent')
    # ### end Alembic commands ###
